apiVersion: v1
kind: Service
metadata:
  name: weather-dashboard-service
spec:
  type: NodePort
  selector:
    app: weather-dashboard
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080
