apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-dashboard-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-dashboard
  template:
    metadata:
      labels:
        app: weather-dashboard
    spec:
      containers:
        - name: weather-dashboard
          image: adititatkare/weather-dashboard:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
